library(ggpubr)
library(dplyr)
library(rstatix)
library(data.table)
library(ggarrange)

dat <- read.table("FigS7_HGOC_TPM_new_GeneLevel_geneSymbol_onlyTumor_log2.txt", row.names=1, header=TRUE)
t_dat <- transpose(dat)
colnames(t_dat) <- rownames(dat)
rownames(t_dat) <- colnames(dat)
t_dat[,"TCF21"] <- as.numeric(t_dat[,"TCF21"])
t_dat[,"TWIST2"] <- as.numeric(t_dat[,"TWIST2"])
t_dat[,"MEOX2"] <- as.numeric(t_dat[,"MEOX2"])
t_dat[,"OSR1"] <- as.numeric(t_dat[,"OSR1"])
t_dat[,"PRRX1"] <- as.numeric(t_dat[,"PRRX1"])
t_dat[,"PRRX2"] <- as.numeric(t_dat[,"PRRX2"])
t_dat[,"TWIST1"] <- as.numeric(t_dat[,"TWIST1"])

pdf("Multiple_boxplot.pdf",7,10)
p1 <- ggplot(t_dat, aes(x=Cluster, y=TCF21, fill=Cluster)) + geom_violin(trim=TRUE) + geom_dotplot(binaxis='y', stackdir='center', dotsize=0.7) + scale_fill_manual(values=c('#000066','#990000'))  + theme_classic()
p2 <- ggplot(t_dat, aes(x=Cluster, y=TWIST2, fill=Cluster)) + geom_violin(trim=TRUE) + geom_dotplot(binaxis='y', stackdir='center', dotsize=0.7) + scale_fill_manual(values=c('#000066','#990000'))  + theme_classic()
p3 <- ggplot(t_dat, aes(x=Cluster, y=MEOX2, fill=Cluster)) + geom_violin(trim=TRUE) + geom_dotplot(binaxis='y', stackdir='center', dotsize=0.7) + scale_fill_manual(values=c('#000066','#990000'))  + theme_classic()
p4 <- ggplot(t_dat, aes(x=Cluster, y=OSR1, fill=Cluster)) + geom_violin(trim=TRUE) + geom_dotplot(binaxis='y', stackdir='center', dotsize=0.7) + scale_fill_manual(values=c('#000066','#990000'))  + theme_classic()
p5 <- ggplot(t_dat, aes(x=Cluster, y=PRRX1, fill=Cluster)) + geom_violin(trim=TRUE) + geom_dotplot(binaxis='y', stackdir='center', dotsize=0.7) + scale_fill_manual(values=c('#000066','#990000'))  + theme_classic()
p6 <- ggplot(t_dat, aes(x=Cluster, y=PRRX2, fill=Cluster)) + geom_violin(trim=TRUE) + geom_dotplot(binaxis='y', stackdir='center', dotsize=0.7) + scale_fill_manual(values=c('#000066','#990000'))  + theme_classic()
p7 <- ggplot(t_dat, aes(x=Cluster, y=TWIST1, fill=Cluster)) + geom_violin(trim=TRUE) + geom_dotplot(binaxis='y', stackdir='center', dotsize=0.7) + scale_fill_manual(values=c('#000066','#990000'))  + theme_classic()

ggarrange(p1, p2, p3, p4, p5, p6, p7, ncol=2, nrow=4)
dev.off()

t_dat %>% wilcox_test(TCF21 ~ Cluster, exact=TRUE, detailed=TRUE, p.adjust.method="bonferroni")
t_dat %>% wilcox_test(TWIST2 ~ Cluster, exact=TRUE, detailed=TRUE, p.adjust.method="bonferroni")
t_dat %>% wilcox_test(MEOX2 ~ Cluster, exact=TRUE, detailed=TRUE, p.adjust.method="bonferroni")
t_dat %>% wilcox_test(OSR1 ~ Cluster, exact=TRUE, detailed=TRUE, p.adjust.method="bonferroni")
t_dat %>% wilcox_test(PRRX1 ~ Cluster, exact=TRUE, detailed=TRUE, p.adjust.method="bonferroni")
t_dat %>% wilcox_test(PRRX2 ~ Cluster, exact=TRUE, detailed=TRUE, p.adjust.method="bonferroni")
t_dat %>% wilcox_test(TWIST1 ~ Cluster, exact=TRUE, detailed=TRUE, p.adjust.method="bonferroni")



dat <- read.table("DCN_PDPN_HGOC_TPM_new_GeneLevel_geneSymbol_onlyTumor_log2.txt", row.names=1, header=TRUE)
t_dat <- transpose(dat)
colnames(t_dat) <- rownames(dat)
rownames(t_dat) <- colnames(dat)
t_dat[,"DCN"] <- as.numeric(t_dat[,"DCN"])
t_dat[,"PDPN"] <- as.numeric(t_dat[,"PDPN"])
pdf("DCN_PDPN_boxplot.pdf",11,7)
p1 <- ggplot(t_dat, aes(x=Cluster, y=DCN, fill=Cluster)) + geom_violin(trim=TRUE) + geom_dotplot(binaxis='y', stackdir='center', dotsize=0.7) + scale_fill_manual(values=c('#000066','#990000'))  + theme_classic()
p2 <- ggplot(t_dat, aes(x=Cluster, y=PDPN, fill=Cluster)) + geom_violin(trim=TRUE) + geom_dotplot(binaxis='y', stackdir='center', dotsize=0.7) + scale_fill_manual(values=c('#000066','#990000'))  + theme_classic()
ggarrange(p1, p2,ncol=2, nrow=1)
dev.off()

t_dat %>% wilcox_test(DCN ~ Cluster, exact=TRUE, detailed=TRUE, p.adjust.method="bonferroni")
t_dat %>% wilcox_test(PDPN ~ Cluster, exact=TRUE, detailed=TRUE, p.adjust.method="bonferroni")

