dat <- read.table("FigS7_HGOC_TPM_new_GeneLevel_geneSymbol_onlyTumor_log2.txt", row.names=1, header=TRUE)
t_dat <- transpose(dat)
colnames(t_dat) <- rownames(dat)
rownames(t_dat) <- colnames(dat)
t_dat[,"TCF21"] <- as.numeric(t_dat[,"TCF21"])
t_dat[,"TWIST2"] <- as.numeric(t_dat[,"TWIST2"])
t_dat[,"MEOX2"] <- as.numeric(t_dat[,"MEOX2"])
t_dat[,"OSR1"] <- as.numeric(t_dat[,"OSR1"])
t_dat[,"PRRX1"] <- as.numeric(t_dat[,"PRRX1"])
t_dat[,"PRRX2"] <- as.numeric(t_dat[,"PRRX2"])
t_dat[,"TWIST1"] <- as.numeric(t_dat[,"TWIST1"])

pdf("Scatterplot_EMT-index_Figure5A.pdf")
p1 <- ggscatter(t_dat, x="EMT_index", y="CDH1", add="reg.line", conf.int=TRUE, cor.coef=TRUE, cor.method="pearson", xlab="EMT index", ylab="ZEB1")
p2 <- ggscatter(t_dat, x="EMT_index", y="CDH2", add="reg.line", conf.int=TRUE, cor.coef=TRUE, cor.method="pearson", xlab="EMT index", ylab="CDH2")
p3 <- ggscatter(t_dat, x="EMT_index", y="VIM", add="reg.line", conf.int=TRUE, cor.coef=TRUE, cor.method="pearson", xlab="EMT index", ylab="VIM")
p4 <- ggscatter(t_dat, x="EMT_index", y="TGFB1", add="reg.line", conf.int=TRUE, cor.coef=TRUE, cor.method="pearson", xlab="EMT index", ylab="TGFB1")
ggarrange(p1, p2, p3, p4, labels=c("A", "B", "C", "D"), ncol=2, nrow=2)
dev.off()
